---
# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "verrazzano-module-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "verrazzano-module-operator.name" . }}
spec:
  ports:
    - name: http-metric
      protocol: TCP
      port: 9100
      targetPort: 9100
  selector:
    app: {{ include "verrazzano-module-operator.name" . }}
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "verrazzano-module-operator.name" . }}-webhook
#  namespace: {{ .Release.Namespace }}
#  labels:
#    app: {{ include "verrazzano-module-operator.name" . }}-webhook
#spec:
#  ports:
#    - name: webhook
#      port: 443
#      targetPort: 9443
#  selector:
#    app: {{ include "verrazzano-module-operator.name" . }}-webhook
