// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/verrazzano/verrazzano-modules/module-operator/apis/platform/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeModuleActions implements ModuleActionInterface
type FakeModuleActions struct {
	Fake *FakePlatformV1alpha1
	ns   string
}

var moduleactionsResource = schema.GroupVersionResource{Group: "platform", Version: "v1alpha1", Resource: "moduleactions"}

var moduleactionsKind = schema.GroupVersionKind{Group: "platform", Version: "v1alpha1", Kind: "ModuleAction"}

// Get takes name of the moduleAction, and returns the corresponding moduleAction object, and an error if there is any.
func (c *FakeModuleActions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModuleAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(moduleactionsResource, c.ns, name), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}

// List takes label and field selectors, and returns the list of ModuleActions that match those selectors.
func (c *FakeModuleActions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModuleActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(moduleactionsResource, moduleactionsKind, c.ns, opts), &v1alpha1.ModuleActionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ModuleActionList{ListMeta: obj.(*v1alpha1.ModuleActionList).ListMeta}
	for _, item := range obj.(*v1alpha1.ModuleActionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested moduleActions.
func (c *FakeModuleActions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(moduleactionsResource, c.ns, opts))

}

// Create takes the representation of a moduleAction and creates it.  Returns the server's representation of the moduleAction, and an error, if there is any.
func (c *FakeModuleActions) Create(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.CreateOptions) (result *v1alpha1.ModuleAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(moduleactionsResource, c.ns, moduleAction), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}

// Update takes the representation of a moduleAction and updates it. Returns the server's representation of the moduleAction, and an error, if there is any.
func (c *FakeModuleActions) Update(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.UpdateOptions) (result *v1alpha1.ModuleAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(moduleactionsResource, c.ns, moduleAction), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeModuleActions) UpdateStatus(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.UpdateOptions) (*v1alpha1.ModuleAction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(moduleactionsResource, "status", c.ns, moduleAction), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}

// Delete takes name of the moduleAction and deletes it. Returns an error if one occurs.
func (c *FakeModuleActions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(moduleactionsResource, c.ns, name, opts), &v1alpha1.ModuleAction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeModuleActions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(moduleactionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ModuleActionList{})
	return err
}

// Patch applies the patch and returns the patched moduleAction.
func (c *FakeModuleActions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModuleAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(moduleactionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}
