// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/verrazzano/verrazzano-modules/module-operator/apis/platform/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeModuleLifecycles implements ModuleLifecycleInterface
type FakeModuleLifecycles struct {
	Fake *FakePlatformV1alpha1
	ns   string
}

var modulelifecyclesResource = schema.GroupVersionResource{Group: "platform", Version: "v1alpha1", Resource: "modulelifecycles"}

var modulelifecyclesKind = schema.GroupVersionKind{Group: "platform", Version: "v1alpha1", Kind: "ModuleAction"}

// Get takes name of the moduleLifecycle, and returns the corresponding moduleLifecycle object, and an error if there is any.
func (c *FakeModuleLifecycles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModuleAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(modulelifecyclesResource, c.ns, name), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}

// List takes label and field selectors, and returns the list of ModuleLifecycles that match those selectors.
func (c *FakeModuleLifecycles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModuleActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(modulelifecyclesResource, modulelifecyclesKind, c.ns, opts), &v1alpha1.ModuleActionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ModuleActionList{ListMeta: obj.(*v1alpha1.ModuleActionList).ListMeta}
	for _, item := range obj.(*v1alpha1.ModuleActionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested moduleLifecycles.
func (c *FakeModuleLifecycles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(modulelifecyclesResource, c.ns, opts))

}

// Create takes the representation of a moduleLifecycle and creates it.  Returns the server's representation of the moduleLifecycle, and an error, if there is any.
func (c *FakeModuleLifecycles) Create(ctx context.Context, moduleLifecycle *v1alpha1.ModuleAction, opts v1.CreateOptions) (result *v1alpha1.ModuleAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(modulelifecyclesResource, c.ns, moduleLifecycle), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}

// Update takes the representation of a moduleLifecycle and updates it. Returns the server's representation of the moduleLifecycle, and an error, if there is any.
func (c *FakeModuleLifecycles) Update(ctx context.Context, moduleLifecycle *v1alpha1.ModuleAction, opts v1.UpdateOptions) (result *v1alpha1.ModuleAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(modulelifecyclesResource, c.ns, moduleLifecycle), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeModuleLifecycles) UpdateStatus(ctx context.Context, moduleLifecycle *v1alpha1.ModuleAction, opts v1.UpdateOptions) (*v1alpha1.ModuleAction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(modulelifecyclesResource, "status", c.ns, moduleLifecycle), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}

// Delete takes name of the moduleLifecycle and deletes it. Returns an error if one occurs.
func (c *FakeModuleLifecycles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(modulelifecyclesResource, c.ns, name, opts), &v1alpha1.ModuleAction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeModuleLifecycles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(modulelifecyclesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ModuleActionList{})
	return err
}

// Patch applies the patch and returns the patched moduleLifecycle.
func (c *FakeModuleLifecycles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModuleAction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(modulelifecyclesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ModuleAction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ModuleAction), err
}
