// Copyright (c) 2023, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/verrazzano/verrazzano-modules/module-operator/apis/platform/v1alpha1"
	scheme "github.com/verrazzano/verrazzano-modules/module-operator/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ModuleActionsGetter has a method to return a ModuleActionInterface.
// A group's client should implement this interface.
type ModuleActionsGetter interface {
	ModuleActions(namespace string) ModuleActionInterface
}

// ModuleActionInterface has methods to work with ModuleAction resources.
type ModuleActionInterface interface {
	Create(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.CreateOptions) (*v1alpha1.ModuleAction, error)
	Update(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.UpdateOptions) (*v1alpha1.ModuleAction, error)
	UpdateStatus(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.UpdateOptions) (*v1alpha1.ModuleAction, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ModuleAction, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ModuleActionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModuleAction, err error)
	ModuleActionExpansion
}

// moduleActions implements ModuleActionInterface
type moduleActions struct {
	client rest.Interface
	ns     string
}

// newModuleActions returns a ModuleActions
func newModuleActions(c *PlatformV1alpha1Client, namespace string) *moduleActions {
	return &moduleActions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the moduleAction, and returns the corresponding moduleAction object, and an error if there is any.
func (c *moduleActions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModuleAction, err error) {
	result = &v1alpha1.ModuleAction{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("moduleactions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ModuleActions that match those selectors.
func (c *moduleActions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModuleActionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ModuleActionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("moduleactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested moduleActions.
func (c *moduleActions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("moduleactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a moduleAction and creates it.  Returns the server's representation of the moduleAction, and an error, if there is any.
func (c *moduleActions) Create(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.CreateOptions) (result *v1alpha1.ModuleAction, err error) {
	result = &v1alpha1.ModuleAction{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("moduleactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(moduleAction).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a moduleAction and updates it. Returns the server's representation of the moduleAction, and an error, if there is any.
func (c *moduleActions) Update(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.UpdateOptions) (result *v1alpha1.ModuleAction, err error) {
	result = &v1alpha1.ModuleAction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("moduleactions").
		Name(moduleAction.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(moduleAction).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *moduleActions) UpdateStatus(ctx context.Context, moduleAction *v1alpha1.ModuleAction, opts v1.UpdateOptions) (result *v1alpha1.ModuleAction, err error) {
	result = &v1alpha1.ModuleAction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("moduleactions").
		Name(moduleAction.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(moduleAction).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the moduleAction and deletes it. Returns an error if one occurs.
func (c *moduleActions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("moduleactions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *moduleActions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("moduleactions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched moduleAction.
func (c *moduleActions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModuleAction, err error) {
	result = &v1alpha1.ModuleAction{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("moduleactions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
