kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: oci
provisioner: oracle.com/oci
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-bv
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: blockvolume.csi.oraclecloud.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-bv-encrypted
provisioner: blockvolume.csi.oraclecloud.com
parameters:
  attachment-type: "paravirtualized"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
